### ISSUE TITLE
alignment with rfc7807bis

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/core-problem-details#13]
The HTTPAPI WG has very recently adopted the rfc7807bis document.  We should monitor what happens there and make sure we  any "lesson learned" in the HTTP world is picked up and digested.

More context:
* [IETF 110 presentation](https://datatracker.ietf.org/meeting/110/materials/slides-110-httpapi-rfc-8707bis-problem-details-00.pdf)
* [RFC7807-bis editor's copy](https://github.com/ietf-wg-httpapi/rfc7807bis)

**Comment by cabo** [comment]
IETF110 presentation: Dead link

**Comment by cabo** [comment]
https://datatracker.ietf.org/meeting/110/materials/slides-110-httpapi-rfc-7807bis-problem-details-00.pdf

**Comment by thomas-fossati** [comment]
The "tunnelling" aspects regarding the 7807->CPD direction have been dealt with in [74cdbf1](https://github.com/core-wg/core-problem-details/pull/16/commits/74cdbf1854d392321ff20a0d5765108a60c20778) (#16)

Until 7807bis is finalised we won't be able to assemble the whole toolkit that is needed to handle the CPD->7807 direction.  This has been noted in the text.
