### ISSUE TITLE
The "x dash" problem

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/core-problem-details#2]
Context: RFC 6648, in particular the analysis in [Appendix B](https://tools.ietf.org/html/rfc6648#appendix-B)

The problem is if the producer never updates to the public format, consumers – not just CoAP clients but the whole logging pipeline – need to cope for an indefinite amount of time.

Unfortunately, consumers don’t seem to have much leverage.

We define a private-to-public migration plan from the onset, but to what extent is that effective in preventing the problem?

We need to provide discussion on strategies for minimising the risk of “eternal pollution” (e.g., use an automated software update mechanism.)

**Comment by cabo** [comment]
-04 of course still has a form of the x-dash problem (for custom problem details entries), but it is minimized as far as we can by strictly separating the "play as I like" space (URIs) from the registered space (numbers).  It is not clear how this can be further improved.
