### ISSUE TITLE
Untagged text strings for human readable text

### ISSUE THREAD

**Issue by cabo** [core-wg/core-problem-details#22]
_Comment by @fpalombini_

[Section 2](https://www.ietf.org/archive/id/draft-ietf-core-problem-details-04.html#section-2):

> Both "title" and "detail" can use either an unadorned CBOR text string (text) or a language-tagged text string (tag38); see Appendix A for the definition of the latter.

I have a hard time motivating why this can be unadorned CBOR text string, given that these two fields are always human-readable text. Maybe we need to add a default, i.e. that when text used, that is to be interpreted as English language is used.

**Comment by cabo** [comment]
(w/ TF:)

making "foo" a shorthand for 38(["en", "foo", false]) makes sense in the Anglo-American dominated world we live in.
 
Details (en? en-US?) need to be discussed though.

**Comment by thomas-fossati** [comment]
> Details (en? en-US?) need to be discussed though.

I wouldn't go down the rabbit hole of also picking the locale.  Too much stress 😅 

I'm happy with the minimum required to satisfy the `langtag` rule, i.e., "en".

**Comment by thomas-fossati** [comment]
In [yesterday's interim](https://datatracker.ietf.org/meeting/interim-2022-core-08/materials/slides-interim-2022-core-08-sessa-carstens-slides-00#page=4) we decided to go with the following:
1. use context if available
2. fall back to english


Now, similar to `base-uri`, should we have a `lang` (and `dir`) keys for when the CPD is stored/forwarded and therefore the context is lost?
