### ISSUE TITLE
Initial SPD suggestion: "offending option number"

### ISSUE THREAD

**Issue by chrysn** [core-wg/core-problem-details#28]
Just having run into a a Bad Option response that was hard to debug without attaching a literal debugger to the program under test (because for some reason all the communication on the net is nowadays encrypted), I'd like to suggest one option for inclusion in the original problem details set:

* Name: Unprocessed CoAP option
* CDDL type: uint | [+uint]
* Brief description: CoAP option number that was not understood
* Longer description: A CoAP option number present in the request that could not be processed by the server. It may be a critical option that the server is unaware of, or an option the server is aware of but could not process (and chose not to, or was not allowed to, ignore it). Several options may be given in a list (in no particular order), without any guarantee that the list is complete (as the server might have stopped processing already at the first problematic option). If an option with the given number was repeated, there is no indication which of the values caused the fault. Clients need to expect seeing options in there they did not send in the request; this can happen if the request traversed a proxy that added the option but did not act on the problem details response. Note that for a few special values of unprocessed CoAP options (such as Accept or Proxy-Uri), there are special response codes (4.06 Not Acceptable, 5.05 Proxying Not Supported, respectively) to be sent instead. For future compatibility, receivers should ignore values not matching the current CDDL type, as these might be used to indicate an option more precisely if the demand arises.

A typical error response with this can be rather short -- just 4.02, 1+2 byte content format, and 3 bytes of CBOR data for option numbers up to 23.

**Comment by cabo** [comment]
CDDL type probably more like `one-or-more<uint>`, where 

``` 
   one-or-more<T> = T / [ 2* T ]
``` 

Should we throw this in now or add this registration later?

**Comment by cabo** [comment]
This case appears to be the only one where RFC 7252 explicitly recommends a diagnostic payload.

The policy is specification required, so we could simply write this up as a document in this repo and register from there.  Of course, including it in the RFC provides more visibility.
