### ISSUE TITLE
Localisation of string fields

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/core-problem-details#3]
How do we handle localisation of text strings?

Some options:
* Force a language (en-us? inuktitut?)
* Add language tags to strings (e.g., a la [CoRAL](https://www.ietf.org/id/draft-ietf-core-coral-03.html#section-6.5))
* "the windows logs" way as suggested by Jim: _"In some ways the method that is used by Windows to log events works out pretty well, but might be too weighty for this.  In that case a list of information with the title and a set of attributes are returned from the server (event) and these are then placed into a localized string.  It might be possible to provide a default string, a set of attributes and a method of getting a localized string if needed."_

**Comment by ektrah** [comment]
See [Expressing Natural Language Texts in CoRAL](https://www.ietf.org/id/draft-ietf-core-coral-03.html#name-expressing-natural-language)

**Comment by thomas-fossati** [comment]
TBD(tho)- split this issue in two.

**Comment by cabo** [comment]
This could be handled by CBOR tags, maybe an update of tag 38

**Comment by thomas-fossati** [comment]
> This could be handled by CBOR tags, maybe an update of tag 38

http://peteroupc.github.io/CBOR/langtags.html

**Comment by chrysn** [comment]
Anything we do for CoRAL that extends this to directions would apply directly here, whether it's in the form of a new tag or a compatible extension to the old one.

**Comment by thomas-fossati** [comment]
or go our own way to avoid deps:

```
text-string = text / intl-text

intl-text = {
  0: text                  ; text 
  1: text                  ; lang tag
  ? 2: bool .default true. ; ltr or rtl
}
```

**Comment by thomas-fossati** [comment]
Dealt with in [e4d1dd2](https://github.com/core-wg/core-problem-details/pull/16/commits/e4d1dd27d66e6a310eddc0e86eeefb40fb9e2b7b) (#16)
