### ISSUE TITLE
Feature: 3rd party error reporting

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/core-problem-details#8]
We discussed the "API gateway" use case where one or more "data centre" backend errors needs to be reported to the client.

Is this a popular enough use case to deserve its own field in the basic part of the map?

Discuss!

**Comment by thomas-fossati** [comment]
When designing this, a (partial) list of things to consider:
* Privacy implications;
* (D)DoS potential (response inflation).

**Comment by cabo** [comment]
On the solution side, composability in the unbundled model (#16) goes a long way, here.

**Comment by thomas-fossati** [comment]
no need to treat this as a separate use case.

> Composability in the unbundled model goes a long way, here.

no need to treat this as a separate use case.
