### ISSUE TITLE
Design goals for protocol elements identification

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/core-problem-details#9]
The variables that needs optimising are:
- size/compactness of IDs
- low barrier to entry
- stability
- private-public transitions
- popularity/familiarity to REST API developers
we don't consider any existing solution that doesn't prevent collisions

**Comment by chrysn** [comment]
Hooking into the request for suggestions in today's presentation (not all points mine but from the meeting):
* Registration at IANA might in future be as easy as a GitHub PR
* Still, we can't expect developers to register every single exception they create.
  * Something hierarchical would solve this. If identifiers (in their expanded form) are URI based, registering a shortcut for a base might allow developers to register their application base and then use codes below that.
* What if a registrant goes away?
  * What if a registrant does updates in incompatible ways?
  * When URI based, same problem as with uncompressed references that are based on DNS. Registrants may prefer to use other URI schemes (eg. URNs without DNS names).

**Comment by thomas-fossati** [comment]
all of the stated design goals are addressed by the design in #16.  The only leftover is "private-public transition" which is tracked by #2
